### ISSUE TITLE
Set discovery plugins in configuration

### ISSUE THREAD

**Issue by tdenewiler** [sscpac/statick-web#4]
To speed up a Statick run when using the configurations provided by web-config.yaml it would help to explicitly list the discovery plugins to use. For example, the `web` level could be

```
levels:
  web:
    discovery:
      javascript:
        flags: ""
      html:
        flags: ""
      css:
        flags: ""
    tool:
      eslint:
        flags: ""
      htmllint:
        flags: ""
      jshint:
        flags: ""
      stylelint:
        flags: ""
```

Similarly, the `web_with_pylint` level could add `python` to the discovery plugins enabled.
